version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sets-app
    ports:
      - "3306:3306"
    volumes:
      - ./database/scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # Use the service name of the MySQL container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "80:80" # Map the phpMyAdmin web interface to port 8080
    depends_on:
      - mysql

  # goapp:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   command: go run /app/main.go
  #   depends_on:
  #     - mysql
